version: '3.8'

services:
  # FastAPI Backend
  api:
    build: .
    container_name: multilingual-ai-api
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - DATABASE_URL=sqlite:///./data/education_assistant.db
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - ollama
    networks:
      - ai-assistant-network
    restart: unless-stopped

  # Streamlit Frontend
  frontend:
    build: .
    container_name: multilingual-ai-frontend
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_HOST=0.0.0.0
      - STREAMLIT_PORT=8501
    command: ["streamlit", "run", "src/frontend/streamlit_app.py", "--server.address=0.0.0.0"]
    depends_on:
      - api
    networks:
      - ai-assistant-network
    restart: unless-stopped

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: multilingual-ai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ai-assistant-network
    restart: unless-stopped

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: multilingual-ai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-assistant-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: multilingual-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
      - frontend
    networks:
      - ai-assistant-network
    restart: unless-stopped

volumes:
  ollama_data:
  redis_data:

networks:
  ai-assistant-network:
    driver: bridge
